import { defineStore } from 'pinia'
import { ref } from 'vue'
export const useClientsStore = defineStore('clients', () => {
  const clients = ref([
    { id: 1,  name: 'Marcus Johnson', initials: 'MJ', plan: 'vip',       lastVisit: '2026-03-05', daysSince: 3,  visits: 48, totalSpend: 4320, preferredBarber: 'Devon R.',  preferredService: 'Signature Cut + Beard',        notes: 'Low fade on sides, keep top longer. Beard: sharp line.',        suggestedUpsell: 'Royal Shave +$35' },
    { id: 2,  name: 'James T.',       initials: 'JT', plan: 'premium',   lastVisit: '2026-02-28', daysSince: 9,  visits: 32, totalSpend: 2848, preferredBarber: 'Devon R.',  preferredService: 'Royal Shave',                  notes: 'Allergic to some aftershave. Use unscented.',                   suggestedUpsell: 'Signature Cut +$65' },
    { id: 3,  name: 'Antoine B.',     initials: 'AB', plan: 'essential', lastVisit: '2026-02-20', daysSince: 17, visits: 18, totalSpend: 882,  preferredBarber: 'Marcus V.', preferredService: 'Haircut + Design',             notes: 'Always wants design on the left side.',                        suggestedUpsell: 'Upgrade to Premium plan' },
    { id: 4,  name: 'Chris W.',       initials: 'CW', plan: 'premium',   lastVisit: '2026-03-02', daysSince: 6,  visits: 25, totalSpend: 2225, preferredBarber: 'Devon R.',  preferredService: 'Fade + Lineup',                notes: 'Skin fade, very precise on the lineup.',                       suggestedUpsell: 'Add beard trim +$25' },
    { id: 5,  name: 'David K.',       initials: 'DK', plan: 'essential', lastVisit: '2026-01-15', daysSince: 52, visits: 9,  totalSpend: 441,  preferredBarber: 'James P.',  preferredService: 'Signature Cut',                notes: "Long-time client, hasn't been in since Jan.",                  suggestedUpsell: 'Win-back: 20% off next visit' },
    { id: 6,  name: 'Michael R.',     initials: 'MR', plan: 'vip',       lastVisit: '2026-03-06', daysSince: 2,  visits: 62, totalSpend: 6200, preferredBarber: 'Devon R.',  preferredService: 'Full Service (Cut+Beard+Shave)', notes: 'VIP — always runs on time. Tip well.',                        suggestedUpsell: 'Monthly product bundle +$40' },
    { id: 7,  name: 'Carlos M.',      initials: 'CM', plan: 'premium',   lastVisit: '2026-03-01', daysSince: 7,  visits: 21, totalSpend: 1869, preferredBarber: 'Marcus V.', preferredService: 'Beard Trim',                   notes: 'Square beard, keep it full.',                                  suggestedUpsell: 'Add hair cut +$55' },
    { id: 8,  name: 'Tyrone B.',      initials: 'TB', plan: 'essential', lastVisit: '2026-02-22', daysSince: 15, visits: 14, totalSpend: 686,  preferredBarber: 'Andre S.',  preferredService: 'Signature Cut',                notes: 'Bald taper, keeps it tight.',                                  suggestedUpsell: 'Beard consultation +$20' },
    { id: 9,  name: 'Jordan T.',      initials: 'JT', plan: 'vip',       lastVisit: '2026-03-04', daysSince: 4,  visits: 37, totalSpend: 3700, preferredBarber: 'Devon R.',  preferredService: 'Signature Cut + Beard',        notes: 'Travelling barber client — always calls ahead.',               suggestedUpsell: 'Refer a friend: +1 free cut' },
    { id: 10, name: 'DeShawn P.',     initials: 'DP', plan: 'premium',   lastVisit: '2026-01-08', daysSince: 59, visits: 6,  totalSpend: 534,  preferredBarber: 'James P.',  preferredService: 'Fade + Lineup',                notes: 'At risk of churn — no visit in 2 months.',                    suggestedUpsell: 'Win-back offer: free beard trim' },
  ])
  return { clients }
})
